add endpoints and test for user
MarianKovalyshyn/library-service-api pull request #15
Opened 2023-10-25 13:49 UTC by OleksandrMoroz24

2023-10-25 14:19 UTC, Kurta97 approved these changes

2023-10-25 17:03 UTC, MarianKovalyshyn requested changes

2023-10-25 17:03 UTC, MarianKovalyshyn commented on customers_service/views.py
> +            raise PermissionDenied("User not authenticated")
I think it's better to use permission_classes = (IsAuthenticated,) here.

2023-10-26 08:40 UTC, MarianKovalyshyn approved these changes

2023-10-26 08:43 UTC, merged